const eventsInit = [
  {
    name: "Don Barriga",
    items: [
      {
        what: "Enchiladas",
        howMuch: 17,
        who: ["Brietta"],
        editing: false,
      },
      {
        what: "Chiles Rellenos",
        howMuch: 18,
        who: ["Nick"],
        editing: false,
      },
      {
        what: "Horchata",
        howMuch: 24,
        who: ["Brietta", "Nick", "Teresa", "Valry"],
        editing: false,
      },
      {
        what: "Gringas",
        howMuch: 14,
        who: ["Barnard"],
        editing: false,
      },
      {
        what: "Birria",
        howMuch: 38,
        who: ["Teresa", "Valry"],
        editing: false,
      },
      {
        what: "Tax+Tip",
        howMuch: 32.86,
        who: ["Brietta", "Valry", "Nick", "Barnard", "Teresa"],
        editing: false,
      },
    ],
  },
  {
    name: "Shady Maple Smorgasbord",
    items: [
      {
        what: "Total",
        howMuch: 206.43,
        who: [
          "Eda",
          "Harmony",
          "Teresa",
          "Valry",
          "Nick",
          "Brietta",
          "Barnard",
        ],
        editing: false,
      },
    ],
  },
  {
    name: "Wakanda Forever",
    items: [
      {
        what: "Movie",
        howMuch: 62.2,
        who: ["Eda", "Harmony", "Teresa", "Barnard", "Chandler"],
        editing: false,
      },
    ],
  },
  {
    name: "Giorgio on Pine",
    items: [
      {
        what: "Bucatini",
        howMuch: 18.5,
        who: ["Teresa"],
        editing: false,
      },
      {
        what: "Spagetti A la Vodka",
        howMuch: 37,
        who: ["Barnard", "Morry"],
        editing: false,
      },
      {
        what: "Linguine & Clams",
        howMuch: 19,
        who: ["Eda"],
        editing: false,
      },
      {
        what: "Rigatoni",
        howMuch: 18.5,
        who: ["Harmony"],
        editing: false,
      },
      {
        what: "Pesto Pizza",
        howMuch: 18,
        who: ["Chandler"],
        editing: false,
      },
      {
        what: "GF Fusili",
        howMuch: 20,
        who: ["Fredi"],
        editing: false,
      },
      {
        what: "Parmesan Crusted Chicken",
        howMuch: 22.75,
        who: ["Fonzie"],
        editing: false,
      },
      {
        what: "Gnocchi",
        howMuch: 19,
        who: ["Curtis"],
        editing: false,
      },
      {
        what: "Espresso",
        howMuch: 3,
        who: ["Teresa"],
        editing: false,
      },
      {
        what: "Cappuccino",
        howMuch: 8,
        who: ["Eda", "Chandler"],
        editing: false,
      },
      {
        what: "Cake Fee",
        howMuch: 20,
        who: [
          "Eda",
          "Harmony",
          "Teresa",
          "Barnard",
          "Chandler",
          "Fonzie",
          "Fredi",
          "Curtis",
          "Morry",
        ],
        editing: false,
      },
      {
        what: "Tax + Tip",
        howMuch: 57.05,
        who: [
          "Eda",
          "Harmony",
          "Teresa",
          "Barnard",
          "Chandler",
          "Fonzie",
          "Fredi",
          "Curtis",
          "Morry",
        ],
        editing: false,
      },
    ],
  },
  {
    name: "Chandler's Costs",
    items: [
      {
        what: "Meal + Movie Refund",
        howMuch: -43,
        who: ["Chandler"],
        editing: false,
      },
      {
        what: "Meal + Movie",
        howMuch: 43,
        who: [
          "Eda",
          "Teresa",
          "Barnard",
          "Fonzie",
          "Curtis",
          "Jilly",
          "Tobie",
          "Diandra",
        ],
        editing: false,
      },
      {
        what: "Cupcakes",
        howMuch: 28.33,
        who: [
          "Eda",
          "Teresa",
          "Barnard",
          "Fonzie",
          "Curtis",
          "Jilly",
          "Tobie",
          "Diandra",
        ],
        editing: false,
      },
    ],
  },
];

const peopleInit = [
  "Eda",
  "Harmony",
  "Teresa",
  "Valry",
  "Nick",
  "Brietta",
  "Barnard",
  "Chandler",
  "Fonzie",
  "Fredi",
  "Curtis",
  "Morry",
  "Jilly",
  "Tobie",
  "Diandra",
];

export { eventsInit, peopleInit };
